version: '3.8'
services:
  node-example:
    build: .
    volumes:
      - ./:/app
    ports:
      - '3000:${PORT}'
    env_file:
      - .env
    # command: pm2-docker start server.js -i max
networks:
  nodes:
    external: false
